version: '3'
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "adminadmin"
    ports:
      - "15432:5432"
    volumes:
      - /home/andremoriya/workspace/docker/postgresql:/var/lib/postgresql/data
    networks:
      - inet
      
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andremoriya@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "adminadmin"
    ports:
      - "16543:80"
    depends_on:
      - postgresql
    networks:
      - inet

networks: 
  inet:
    driver: bridge
