version: '3'
services:
  postgres-compose:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "PASSWORD"
    ports:
      - "15432:5432"
    volumes:
      - /home/andremoriya/workspace/docker/postgresql:/var/lib/postgresql/data
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andremoriya@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PASSWORD"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose

networks: 
  postgres-compose-network:
    driver: host
